version: '3'

services:

  laravel:
    build: 
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: p3d50/laravel:prod
    container_name: laravel
    networks:
      [laranet]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod 
    image: p3d50/nginx:prod
    container_name: nginx-proxxy-reverso
    networks:
      [laranet]
    ports: 
      ["8080:80"]

networks:
  laranet: 
    driver: bridge
